### ISSUE TITLE
停在 "ONLY_ACTIVE_ARCH = NO" 不动

### ISSUE THREAD

**Issue by bullda** [webfrogs/xcode_shell#17]
非常棒的项目, 感谢.

试用过程中出现一个问题, 会卡在 "ONLY_ACTIVE_ARCH = NO" 不动, 不知道是否是环境问题, 希望能给予一些帮助, 谢谢.

执行: 

~/xcode_shell/cocoapods-build . Debug

Log:

Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/xxx/builds/0c5e0783/0/xxx/xxx-iOS/build/Debug-iphoneos
    ONLY_ACTIVE_ARCH = NO

**Comment by beiliubei** [comment]
+1

**Comment by beiliubei** [comment]
@bullda 执行下 pod install 就可以了
