### ISSUE TITLE
不支持xcodebuild的PROVISIONING_PROFILE参数

### ISSUE THREAD

**Issue by ChenTF** [webfrogs/xcode_shell#18]
我想制定xcodebuild的PROVISIONING_PROFILE参数. 发现不支持. 还麻烦添加一下.

**Comment by ChenTF** [comment]
I want to set the PROVISIONING_PROFILE parameters of xcodebuild. but not supported.  
Would you please add it. Thanks

**Comment by webfrogs** [comment]
hi，建议去了解一下 fastlane 下的 gym 项目，用那个更方便哦～

**Comment by ChenTF** [comment]
哦. 非常感谢, 回头了解下. 
我修改了下ipa-build.sh文件, 新添了一个-m参数, 让它支持了PROVISIONING_PROFILE参数设置.  
[ipa-build.zip](https://github.com/webfrogs/xcode_shell/files/406588/ipa-build.zip)
