### ISSUE TITLE
如果工程用的是cocopads管理的 那么运行buld就会报错 

### ISSUE THREAD

**Issue by ws1227** [webfrogs/xcode_shell#23]
如我的项目名字是GYBaseDemo然后报错结果是
The following build commands failed:
	Ld build/GYNewDemo.build/Release-iphoneos/GYNewDemo.build/Objects-normal/armv7/GYNewDemo normal armv7
	Ld build/GYNewDemo.build/Release-iphoneos/GYNewDemo.build/Objects-normal/arm64/GYNewDemo normal arm64
请问如何解决

**Comment by webfrogs** [comment]
本项目已经停止更新。建议使用 fastlane 的 gem 来完成自动打包。 https://github.com/fastlane/fastlane/tree/master/gym#readme
