### ISSUE TITLE
./cocoapods-build . Release  wrong

### ISSUE THREAD

**Issue by burning-git** [webfrogs/xcode_shell#24]
The following build commands failed:
	CompileC /Users/gitburning/Library/Developer/Xcode/DerivedData/LingDiApp-entpsiisisurszfnszbjhllsgfef/Build/Intermediates/LingDiApp.build/Release-iphoneos/LingDiApp.build/Objects-normal/armv7/BaseViewModel.o LingDiApp/Function/BaseViewModel/BaseViewModel.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

I build project  wrong with use  './cocoapods-build . Release',,, can you help me?

**Comment by webfrogs** [comment]
Thanks for using this project.but it has stopped updating. Use fastlane gem instead. https://github.com/fastlane/fastlane/tree/master/gym#readme
