### ISSUE TITLE
solve custom configuration name can not make a ipa

### ISSUE THREAD

**Issue by Derkin** [webfrogs/xcode_shell#7]
i define a build config named ‘ad-hoc’,and run the script but can not
get a ipa at directory ipa-build .and after check ,i find if i change
the appdirname use my way ,it will generate a ipa.
## change this:
# build文件夹路径

build_path=${project_path}/build
# 生成的app文件目录

appdirname=Release-iphoneos
if [ $build_config = Debug ];then
    appdirname=Debug-iphoneos
fi
if [ $build_config = Distribute ];then
    appdirname=Distribute-iphoneos

**Comment by Marcusias** [comment]
你好,我想打包为 Enterprise Deployment  请问该如何配置?

**Comment by ChenTF** [comment]
ipa-build的-c参数就是用来修改这个的. 传Distribute @Marcusias
